# Generated by Django 5.2.7 on 2025-11-13 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(blank=True, max_length=200, null=True)),
                ('rut_empresa', models.CharField(blank=True, max_length=12, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('ADM', 'Administrador'), ('CON', 'Conductor'), ('MEC', 'Mecánico'), ('AUX', 'Auxiliar'), ('GER', 'Gerente')], max_length=3)),
                ('estado', models.CharField(choices=[('DIS', 'Disponible'), ('RUT', 'En Ruta'), ('LIC', 'Licencia'), ('VAC', 'Vacaciones'), ('PER', 'Permiso')], default='DIS', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado_profile', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='api.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('capacidad', models.CharField(choices=[('MC', 'Mediana Capacidad'), ('GC', 'Gran Capacidad')], max_length=2)),
                ('estado', models.CharField(choices=[('DIS', 'Disponible'), ('RUT', 'En Ruta'), ('MAN', 'En Mantención'), ('REP', 'En Reparación')], default='DIS', max_length=3)),
                ('conductor_asignado', models.ForeignKey(blank=True, limit_choices_to={'cargo': 'CON'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camion_asignado', to='api.empleado')),
                ('sucursal_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camiones_en_base', to='api.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=255)),
                ('tipo_carga', models.CharField(help_text='Ej: Alimentos, Retail, Agrícola', max_length=100)),
                ('peso_kg', models.DecimalField(decimal_places=2, help_text='Peso total de la carga en kilogramos (kg)', max_digits=10)),
                ('volumen_m3', models.DecimalField(decimal_places=2, help_text='Volumen total de la carga en metros cúbicos (m³)', max_digits=10)),
                ('detalles_carga', models.TextField(blank=True, help_text='Dimensiones, fragilidad, etc.', null=True)),
                ('fecha_deseada', models.DateField(help_text='Fecha en que el cliente quiere el transporte')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('COTIZADO', 'Cotizado'), ('CONFIRMADO', 'Confirmado'), ('EN_RUTA', 'En Ruta'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_cotizado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('camion_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to='api.camion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='api.cliente')),
                ('sucursal_origen', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_originados', to='api.sucursal')),
            ],
        ),
    ]
